version: '2'
services:
  app:
    image: 'spring-boot-docker:latest'
    container_name: spring-boot-docker
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1111