spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: jamesedthawut98
    password: xzteahntfubhczea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  token:
    secret: secret
    issuer: backend